# Generated by Django 4.2.5 on 2023-10-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('fightid', models.AutoField(db_column='FightId', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
                ('win_id', models.ImageField(db_column='WinnerId', upload_to='')),
                ('poke_id', models.ImageField(db_column='PokeId', upload_to='')),
                ('enemy_id', models.ImageField(db_column='EnemyId', upload_to='')),
            ],
            options={
                'db_table': 'fights',
            },
        ),
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
