# Generated by Django 4.2.5 on 2023-10-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0002_fight_delete_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='fightid',
            field=models.IntegerField(db_column='FightId', primary_key=True, serialize=False),
        ),
    ]
