# Generated by Django 4.2.5 on 2023-10-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_alter_fight_fightid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='fightid',
            field=models.IntegerField(db_column='FightId', primary_key=True, serialize=False),
        ),
    ]
