# Generated by Django 4.2.5 on 2023-10-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0005_alter_fight_fightid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(db_column='FightId', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name')),
                ('url', models.CharField(db_column='Url')),
                ('image', models.CharField(db_column='Image')),
                ('hp', models.IntegerField(db_column='Hp')),
                ('attack', models.IntegerField(db_column='Attack')),
                ('speed', models.IntegerField(db_column='Speed')),
            ],
            options={
                'db_table': 'pokemons',
            },
        ),
    ]
