# Generated by Django 4.2.5 on 2023-10-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0006_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.IntegerField(db_column='Id', primary_key=True, serialize=False),
        ),
    ]
