{
 "title": "Pokemons",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Статистика",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Общее количество боев\", AVG(\"CountRound\") AS \"Среднее количество раундов\" FROM fights LIMIT 50 "
    }
   ]
  },
  {
   "title": "Топ-5 покемонов по количеству побед",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT pokemons.\"Name\" AS \"Имя покемона\", COUNT(\"WinnerId\") AS \"Количество побед\" \nFROM fights JOIN pokemons ON fights.\"WinnerId\" = \"Id\"::varchar  \nGROUP BY \"WinnerId\", pokemons.\"Name\"\nORDER BY COUNT(\"WinnerId\") DESC \nLIMIT 5"
    }
   ]
  },
  {
   "title": "Количество проведенных боев по дням за последнюю неделю",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"Date\" AS \"Дата\", COUNT(*) AS \"Количество боев\" FROM fights GROUP BY \"Date\" ORDER BY \"Date\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Количество раундов по дням за последнюю неделю",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT SUM(\"CountRound\") AS \"Сумма кол-ва боев\", \"Date\" FROM fights GROUP BY \"Date\" LIMIT 50 "
    }
   ]
  }
 ]
}